const Event = require('../models/Events');
const Expenses = require('../models/Expenses');

/**
 * Function 1: Calculate revenue and direct costs (COGS) from events
 */
const getEventFinancials = async (startDate, endDate) => {
  const financials = await Event.aggregate([
    // 1. Filter events by date range
    {
      $match: {
        eventDate: { $gte: startDate, $lte: endDate }
      }
    },
    // 2. Join the EventActual model to get the specific costs for each event
    {
      $lookup: {
        from: "eventactuals", // The MongoDB collection name (usually lowercase plural)
        localField: "_id",
        foreignField: "event",
        as: "actualData"
      }
    },
    // 3. Unwind the array returned from the lookup. 
    // We filter out events without an EventActual (meaning they haven't occurred or aren't financially closed yet).
    {
      $unwind: {
        path: "$actualData",
        preserveNullAndEmptyArrays: false 
      }
    },
    // 4. Group and summarize all data into a single object
    {
      $group: {
        _id: null,
        eventCount: { $sum: 1 },
        totalRevenue: { $sum: "$price" }, // The event price charged to the customer
        totalWages: { $sum: "$actualData.totalWages" },
        totalAlcohol: { $sum: "$actualData.totalAlcoholExpenses" },
        totalIce: { $sum: "$actualData.totalIceExpenses" },
        totalEventGeneral: { $sum: "$actualData.totalGeneralExpenses" },
        totalDirectCosts: { $sum: "$actualData.totalExpenses" } // Total direct costs of the event
      }
    }
  ]);

  // If no events are found in the range, return zeros
  if (financials.length === 0) {
    return {
      eventCount: 0,
      totalRevenue: 0, totalWages: 0, totalAlcohol: 0, 
      totalIce: 0, totalEventGeneral: 0, totalDirectCosts: 0
    };
  }

  // Remove the _id field automatically generated by Mongo in the group stage
  const data = financials[0];
  delete data._id;
  return data;
};

/**
 * Function 2: Calculate general operational expenses (OPEX)
 */
const getOperationalExpenses = async (startDate, endDate) => {
  const expenses = await Expenses.aggregate([
    // 1. Filter by date and only include actually paid expenses
    {
      $match: {
        date: { $gte: startDate, $lte: endDate },
        waspaid: true
      }
    },
    // 2. Group and summarize by category
    {
      $group: {
        _id: "$category",
        totalAmount: { $sum: "$price" } // Using the price field as defined in your model
      }
    }
  ]);

  const categoryStats = {};
  let totalOpex = 0;

  // Format the data into an object that is easy for the Frontend to read (e.g., for a pie chart)
  expenses.forEach(exp => {
    categoryStats[exp._id] = exp.totalAmount;
    totalOpex += exp.totalAmount;
  });

  return { categoryStats, totalOpex };
};

module.exports = {
  getEventFinancials,
  getOperationalExpenses
};